-- =====================================================================
-- Karacena 2026 — "Faire corps" — MySQL schema (migration 001)
-- Charset utf8mb4 for full French/Arabic support
-- =====================================================================
CREATE DATABASE IF NOT EXISTS karacena_2026
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE karacena_2026;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','editor') DEFAULT 'editor',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS venues (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name_fr VARCHAR(180) NOT NULL,
  name_en VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  address_fr VARCHAR(255), address_en VARCHAR(255),
  description_fr TEXT, description_en TEXT,
  latitude DECIMAL(10,7), longitude DECIMAL(10,7),
  capacity INT,
  access_info_fr TEXT, access_info_en TEXT,
  image_url VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS artists (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  country VARCHAR(100),
  discipline VARCHAR(180),
  bio_fr TEXT, bio_en TEXT,
  photo_url VARCHAR(500),
  website_url VARCHAR(500),
  is_company TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS shows (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title_fr VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  category ENUM('AMESIP','LAUREATS','INTERNATIONAL') NOT NULL,
  summary_fr TEXT, summary_en TEXT,
  description_fr LONGTEXT, description_en LONGTEXT,
  duration_minutes INT, age_minimum INT,
  poster_url VARCHAR(500),
  teaser_video_url VARCHAR(500),
  gallery_json JSON,
  price_mad DECIMAL(8,2) DEFAULT 0,
  is_free TINYINT(1) DEFAULT 0,
  is_featured TINYINT(1) DEFAULT 0,
  is_published TINYINT(1) DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_shows_category (category),
  INDEX idx_shows_featured (is_featured)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS show_artists (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  show_id INT UNSIGNED NOT NULL,
  artist_id INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_show_artist (show_id, artist_id),
  FOREIGN KEY (show_id) REFERENCES shows(id) ON DELETE CASCADE,
  FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS show_dates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  show_id INT UNSIGNED NOT NULL,
  venue_id INT UNSIGNED,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME,
  seats_total INT NOT NULL DEFAULT 200,
  seats_booked INT NOT NULL DEFAULT 0,
  status ENUM('SCHEDULED','SOLD_OUT','CANCELLED') DEFAULT 'SCHEDULED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_show_dates_start (starts_at),
  FOREIGN KEY (show_id) REFERENCES shows(id) ON DELETE CASCADE,
  FOREIGN KEY (venue_id) REFERENCES venues(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bookings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(20) NOT NULL UNIQUE,
  show_date_id INT UNSIGNED,
  customer_name VARCHAR(180) NOT NULL,
  customer_email VARCHAR(180) NOT NULL,
  customer_phone VARCHAR(40),
  type ENUM('SINGLE','PASS') DEFAULT 'SINGLE',
  quantity INT NOT NULL DEFAULT 1,
  total_mad DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_method ENUM('CMI','PAYPAL','ONSITE') DEFAULT 'ONSITE',
  payment_status ENUM('PENDING','PAID','FAILED','REFUNDED') DEFAULT 'PENDING',
  payment_ref VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (show_date_id) REFERENCES show_dates(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tickets (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  booking_id INT UNSIGNED NOT NULL,
  code VARCHAR(64) NOT NULL UNIQUE,
  qr_data_url MEDIUMTEXT,
  holder_name VARCHAR(180),
  status ENUM('VALID','USED','CANCELLED') DEFAULT 'VALID',
  scanned_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS blog_posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  author_id INT UNSIGNED,
  title_fr VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  category ENUM('NEWS','PORTRAIT','BACKSTAGE','INTERVIEW','VIDEO') DEFAULT 'NEWS',
  excerpt_fr TEXT, excerpt_en TEXT,
  body_fr LONGTEXT, body_en LONGTEXT,
  cover_url VARCHAR(500),
  video_url VARCHAR(500),
  is_published TINYINT(1) DEFAULT 0,
  published_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS partners (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  type ENUM('INSTITUTIONAL','SPONSOR','MEDIA') NOT NULL,
  logo_url VARCHAR(500),
  website_url VARCHAR(500),
  description_fr TEXT, description_en TEXT,
  display_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(180) NOT NULL UNIQUE,
  locale ENUM('fr','en') DEFAULT 'fr',
  is_confirmed TINYINT(1) DEFAULT 1,
  unsubscribed_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contact_messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  subject VARCHAR(255),
  message TEXT NOT NULL,
  status ENUM('NEW','READ','REPLIED') DEFAULT 'NEW',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS press_accreditations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(40),
  media_outlet VARCHAR(255) NOT NULL,
  media_type ENUM('PRESS','TV','RADIO','WEB','PHOTO','OTHER') DEFAULT 'PRESS',
  country VARCHAR(100),
  message TEXT,
  status ENUM('PENDING','APPROVED','REJECTED') DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS atabadoul_registrations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(40),
  organization VARCHAR(255),
  role VARCHAR(180),
  country VARCHAR(100),
  interests TEXT,
  wants_directory TINYINT(1) DEFAULT 0,
  directory_bio TEXT,
  status ENUM('PENDING','CONFIRMED','CANCELLED') DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS historical_editions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  year INT NOT NULL UNIQUE,
  edition_number INT NOT NULL,
  theme_fr VARCHAR(255) NOT NULL,
  theme_en VARCHAR(255) NOT NULL,
  description_fr TEXT, description_en TEXT,
  cover_url VARCHAR(500),
  gallery_json JSON,
  video_url VARCHAR(500),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS media_files (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255),
  mime_type VARCHAR(120),
  size_bytes INT,
  url VARCHAR(500) NOT NULL,
  alt_fr VARCHAR(255), alt_en VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS translations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  namespace VARCHAR(80) DEFAULT 'common',
  key_name VARCHAR(180) NOT NULL,
  fr TEXT, en TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_translation (namespace, key_name)
) ENGINE=InnoDB;
